// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCKMW3Cn3mU8SuRFSeWQa6rbv1y5yuirk',
    appId: '1:736971431217:web:30356a5434227de823e410',
    messagingSenderId: '736971431217',
    projectId: 'lifelink-997ca',
    authDomain: 'lifelink-997ca.firebaseapp.com',
    storageBucket: 'lifelink-997ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt5b328KIWhlbThkT12AfqnuugPEftA4A',
    appId: '1:736971431217:ios:9fa14741e149e65c23e410',
    messagingSenderId: '736971431217',
    projectId: 'lifelink-997ca',
    storageBucket: 'lifelink-997ca.firebasestorage.app',
    iosBundleId: 'com.example.lifelink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt5b328KIWhlbThkT12AfqnuugPEftA4A',
    appId: '1:736971431217:ios:9fa14741e149e65c23e410',
    messagingSenderId: '736971431217',
    projectId: 'lifelink-997ca',
    storageBucket: 'lifelink-997ca.firebasestorage.app',
    iosBundleId: 'com.example.lifelink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCKMW3Cn3mU8SuRFSeWQa6rbv1y5yuirk',
    appId: '1:736971431217:web:4513cdae818340fd23e410',
    messagingSenderId: '736971431217',
    projectId: 'lifelink-997ca',
    authDomain: 'lifelink-997ca.firebaseapp.com',
    storageBucket: 'lifelink-997ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmsFmwlUEAzxOqs3q58l3xdjRrV0mCLtw',
    appId: '1:736971431217:android:e63e211535e508af23e410',
    messagingSenderId: '736971431217',
    projectId: 'lifelink-997ca',
    storageBucket: 'lifelink-997ca.firebasestorage.app',
  );

}